# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: Build
    jobs:
      - job: 'Validation'
        pool:
          vmimage: windows-latest
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'XsltARM-conn'
              subscriptionId: '5bd3f162-a030-443f-b431-3a6f5e8e23a3'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'XsltARM-rg'
              location: 'Southeast Asia'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/XMLTemplate/template.json'
              csmParametersFile: '$(Build.SourcesDirectory)/XMLTemplate/parameters.json'
              deploymentMode: 'Validation'
              
  - stage: Deploy
    condition:
      and(
       succeeded(), 
       eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    dependsOn:
     Build
    jobs:
      - job: "Deployment"
        pool:
          vmimage: windows-latest
        steps: 
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'XsltARM-conn'
              subscriptionId: '5bd3f162-a030-443f-b431-3a6f5e8e23a3'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'XsltARM-rg'
              location: 'Southeast Asia'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/XMLTemplate/template.json'
              csmParametersFile: '$(Build.SourcesDirectory)/XMLTemplate/parameters.json'
              deploymentMode: 'Incremental'